[project]
name = "pizza-los-viernes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "juanpabloramirez212410", email = "juanpapi421@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.61.1",
]

[project.scripts]
pizza-los-viernes = "pizza_los_viernes:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
